# Use only before the first certificate has been issued.
server {
    listen 80;
    server_name weekly-lab.com www.weekly-lab.com;

    root /usr/share/nginx/weekly-lab;
    index index.html;
    expires -1;

    location / {
        try_files $uri $uri/ =404;
    }
}
